-- Convert month number to month name
order_month_name = 
SWITCH(
    TRUE(),
    'e_commerce_data_bi_dashboard'[order_month] = 1, "Jan",
    'e_commerce_data_bi_dashboard'[order_month] = 2, "Feb",
    'e_commerce_data_bi_dashboard'[order_month] = 3, "Mar",
    'e_commerce_data_bi_dashboard'[order_month] = 4, "Apr",
    'e_commerce_data_bi_dashboard'[order_month] = 5, "May",
    'e_commerce_data_bi_dashboard'[order_month] = 6, "Jun",
    'e_commerce_data_bi_dashboard'[order_month] = 7, "Jul",
    'e_commerce_data_bi_dashboard'[order_month] = 8, "Aug",
    'e_commerce_data_bi_dashboard'[order_month] = 9, "Sep",
    'e_commerce_data_bi_dashboard'[order_month] = 10, "Oct",
    'e_commerce_data_bi_dashboard'[order_month] = 11, "Nov",
    'e_commerce_data_bi_dashboard'[order_month] = 12, "Dec",
    BLANK() -- Return BLANK for any unexpected values
)

-- Define order is ontime or not
ontime_or_not =  
IF(
    ISBLANK(e_commerce_data_bi_dashboard[leadtime_expected]),
    BLANK(), -- Handle cases where leadtime_expected is not available
    IF(
        e_commerce_data_bi_dashboard[logistics_leadtime] <= e_commerce_data_bi_dashboard[leadtime_expected],
        "On-Time",
        "Late"
    )
)

-- Convert discount from float format to string format (e.g. 80.0%) 
discount_percentage = FORMAT(e_commerce_data_bi_dashboard[percent_discount_percent]/100, "0.0%")



